### ISSUE TITLE
numeric endpoint in multivisit/two-arm study

### ISSUE THREAD

**Issue by rietzlers** [rietzlers/reporter#3]
Ich habe einen ersten Entwurf für einen Report erstellt, der als Diskussionsgrundlage dienen soll.
Siehe: https://github.com/rietzlers/reporter/blob/bca86298ee373f09c382198036ebb3213c5948a2/notebooks/mock_report_numeric_endpoint.Rmd#L2

Ich denke die wesentlichen Standard-Statistiken und -Graphiken für einen numerischen Endpunkt in einer multivisit/two-arm Studie sind vorhanden.

**Comment by wadepuhlm** [comment]
Achtung, einearmige Studien sind im Moment wichtiger!

**Comment by rietzlers** [comment]
Darauf beschränken wir uns jetzt auch zunächst.
