### ISSUE TITLE
Report-Tabelle t.test diff to baseline

### ISSUE THREAD

**Issue by wadepuhlm** [rietzlers/reporter#5]
Es fehle descriptive Statistiken, nämlich
- Quartile
- Standardabweichung
- Mittelwert

**Comment by rietzlers** [comment]
diese statistiken werden nun mit berichtet.

**Comment by wadepuhlm** [comment]
Darstellung in Tabellen:

Optimale Anordnung der Spalten metrisch:
Visitname  - Raw - Mean +- Standard deviation - Median [1.Quartile -3-Quartile)  - Range: Min- Max
Visit Difference - see above additionally Teststatisitic - Degree fo freedom - p-Value

Optimale Anordnung der Spalten kategoriell:
Visit - Level x1 absolute/relativ - Level x2 absolute/relativ - type of test - test statistic - p-value
Es sollte möglich sein McNemar oder Bowker je nach Anzahl der Lewel (= Ausprägungen) zu wählen
2 Ausprägungen (z.B. Ja/Nein) -> McNemar
>2 Ausprägungen (z.B. none - minimal - moderate - severe) -> Bowker 

Altes Thema: Anzahl der Nachkommastellen:
Es haben sich folgende Prinzipien bewährt und mit NVT eingespielt und erleichtern das formatieren der Tabellen:
- Sie werden für den Tabellenteil generell festgelegt (sonst gibt nur endlose Disussionen!)
- Im vom Sponsor gmeachten Bericht werden die Nachkommastellen sinnvol angepasst
- Nur für wenige Laborwerte waren Anpassungen offensichtlich, aber letztlich kann man wegen dem obigen Punkt auch gut mit "schräg" aussehenden Tabllen leben.
- Im Detail:
   - Metrische Werte: 3 Nachkommastellen
   - Prozentwerte: 2 Nachkommastellen
   - P-Werte: 4 Nachkommastellen
